function loadAssets() {
  loadSpriteAtlas("./assets/characters.png", {
    "player-down": { x: 0, y: 82, width: 16, height: 16 },
    "player-up": { x: 16, y: 82, width: 16, height: 16 },
    "player-side": {
      x: 0,
      y: 98,
      width: 32,
      height: 16,
      sliceX: 2,
      sliceY: 1,
      anims: { walk: { from: 0, to: 1, speed: 6 } },
    },
    npc: { x: 32, y: 98, width: 16, height: 16 },
    "cat-mon": { x: 0, y: 16, width: 32, height: 32 },
    "spider-mon": { x: 32, y: 16, width: 32, height: 32 },
    "centipede-mon": { x: 64, y: 16, width: 32, height: 32 },
    "grass-mon": { x: 0, y: 49, width: 32, height: 32 },
    "mushroom-mon": { x: 32, y: 49, width: 32, height: 32 },
    "mini-mons": {
      x: 0,
      y: 0,
      width: 128,
      height: 16,
      sliceX: 8,
      sliceY: 1,
      anims: { spider: 1, centipede: 2, grass: 3 },
    },
  }),
  loadSprite("battle-background", "./assets/battle-background.png"),
  loadSprite("coin", "./assets/coin.png"),
  loadSpriteAtlas("./assets/deck.png", {
    cards: {
      x: 0,
      y: 0,
      width: 896,
      height: 256,
      sliceX: 14,
      sliceY: 4,
      anims: {
        "A-diamond": 0,
        "2-diamond": 1,
        "3-diamond": 2,
        "4-diamond": 3,
        "5-diamond": 4,
        "6-diamond": 5,
        "7-diamond": 6,
        "8-diamond": 7,
        "9-diamond": 8,
        "10-diamond": 9,
        "J-diamond": 10,
        "Q-diamond": 11,
        "K-diamond": 12,
        "A-heart": 14,
        "2-heart": 15,
        "3-heart": 16,
        "4-heart": 17,
        "5-heart": 18,
        "6-heart": 19,
        "7-heart": 20,
        "8-heart": 21,
        "9-heart": 22,
        "10-heart": 23,
        "J-heart": 24,
        "Q-heart": 25,
        "K-heart": 26,
        "A-club": 28,
        "2-club": 29,
        "3-club": 30,
        "4-club": 31,
        "5-club": 32,
        "6-club": 33,
        "7-club": 34,
        "8-club": 35,
        "9-club": 36,
        "10-club": 37,
        "J-club": 38,
        "Q-club": 39,
        "K-club": 40,
        "A-spade": 42,
        "2-spade": 43,
        "3-spade": 44,
        "4-spade": 45,
        "5-spade": 46,
        "6-spade": 47,
        "7-spade": 48,
        "8-spade": 49,
        "9-spade": 50,
        "10-spade": 51,
        "J-spade": 52,
        "Q-spade": 53,
        "K-spade": 54,
        "face-down": 55,
      }
    }
  }),
  loadSpriteAtlas("./assets/tiles.png", {
    tile: {
      x: 0,
      y: 0,
      width: 128,
      height: 128,
      sliceX: 8,
      sliceY: 8,
      anims: {
        "bigtree-pt1": 1,
        "bigtree-pt2": 2,
        "bigtree-pt3": 9,
        "bigtree-pt4": 10,
        "grass-m": 14,
        "grass-tl": 17,
        "grass-tm": 18,
        "grass-tr": 19,
        "grass-l": 25,
        "grass-r": 27,
        "grass-bl": 33,
        "grass-mb": 34,
        "grass-br": 35,
        "tree-t": 4,
        "tree-b": 12,
        "grass-water": 20,
        "sand-1": 6,
        "ground-l": 41,
        "ground-m": 42,
        "ground-r": 43,
        "rock-water": 60,
      },
    },
  });
}